#!/bin/bash
trap "rm -f $$*" SIGHUP SIGINT SIGTERM	#traps kill command
echoerr() { echo "$@" 1>&2; rm -f $$*; exit 1; }	#to print errors to screen
printCol(){ echo $1; while read line; do echo -e -n "$line\t"; done < $2; echo -e "\n"; }	#prints column data
findMedSumAvg(){ tmpcnt=1; sum=0;
	while read num; do
		if [[ $tmpcnt == $(( ($2 / 2) + 1 )) ]]; then med=$num; fi	#saves median value
		tmpcnt=`expr $tmpcnt + 1`; sum=`expr $sum + $num` #adds number to sum total
	done < <(sort -n $1)
	avg=$(( ($sum + ($2 / 2)) / $2 )); }	#finds average
datafilepath="$$datafile"
if [ "$#" = "1" ]; then cat > $datafilepath		#if it should be read from stdin
elif [ "$#" = "2" ]; then datafilepath=$2		#if it should be read from provided file
else echoerr "./stats {-rows|-cols} [file]"; fi	#if too many or too few options are provided
if [[ ! -e $datafilepath ]] || [[ ! -r $datafilepath ]] || [[ ! -f $datafilepath ]]; then echoerr "./stats cannot read $datafilepath"; fi	#checks that file exists and has read permission
if [[ `wc -c < $datafilepath` == 0 ]]; then echoerr "FILE IS EMPTY"; fi	#checks if file is empty
rowCount=1; colCount=1; #numRows=$((wc -l < $datafilepath)); #numCols=$((head -1 $datafilepath | wc -w));
if [[ $1 == -r* ]]; then	#Code to calculate for rows
	echo -e "Average\tMedian"	#print headers
	while [ "$rowCount" -le "`cat $datafilepath | wc -l`" ]; do
		head -$rowCount $datafilepath | tail -1 | tr "\t" "\n" > $$temprow
		findMedSumAvg $$temprow `head -1 $datafilepath | wc -w`	#passes temp file and number of columns
		echo -e "$avg\t$med"	#prints results
		rowCount=`expr $rowCount + 1`; done
elif [[ $1 == -c* ]]; then	#Code to calculate for columns
	while [ "$colCount" -le "`head -1 $datafilepath | wc -w`" ]; do
		cut -f $colCount $datafilepath > $$tempcol
		findMedSumAvg $$tempcol `cat $datafilepath | wc -l`	#passes temp file and number of rows
		echo -e $med >> $$tempMedian	#adds medians to temp file
		echo -e $avg >> $$tempAverage	#adds averages to temp file
		colCount=`expr $colCount + 1`; done
	printCol "Averages:" $$tempAverage
	printCol "Medians:" $$tempMedian
else echoerr "./stats {-rows|-cols} [file]"; fi; rm -f $$*	#prints error if neither rows nor columns are specified