#!/bin/sh


echoerr() { echo "$@" 1>&2; }

datafilepath="datafile$$"
if [ "$#" = "1" ]
then
    cat > "$datafilepath"
elif [ "$#" = "2" ]
then
    datafilepath=$2
fi

#Code to calculate for rows
if [[ $1 == -r* ]];
then
    echo "calculating row stats";
    echo -e "Average \t Median"
    while read i #reads all lines
    do
	sum=0
	count=0
	for num in $i
	do
	  sum=$(($sum + $num)) #adds number to sum total
	  if [[ $count == 0 ]] #move vales to temp file for sorting
	  then
		echo "$num" > $$tempfile #if first line then restart file
	  else
	  	echo "$num" >> $$tempfile #otherwise add to file
	  fi
	  count=$(($count + 1))
	done
	avg=$(($sum / $count)) 
        rem=$(($sum % $count))
	while (($rem > ($count / 2))) #checks is average needs rounded up
        do
          avg=$(($avg + 1))
          rem=0
        done

	med=$(($count / 2 + 1))
	
	sort -n $$tempfile -o $$tempsorted #sorts temp file

	tmpcnt=0
	while read tempnum   #finds median
	do
	 tmpcnt=$((tmpcnt + 1))
	 if [[ $med == $tmpcnt ]]
	 then
		med=$tempnum
	 fi
	done < $$tempsorted
	
	echo -e "$avg \t\t $med" #prints results
	rm -f $$tempfile   #deletes temp files
	rm -f $$tempsorted
    done < $2
    echoerr 0
	
#calculates column info
elif [[ $1 == -c* ]];
then
   echo "calculating column stats";
    numrows=0
    while read i  #saves each column to separate temp files and sorts each
    do
	numcols=0
        for num in $i
        do
	  echo "$num" >> $$tempfile$numcols
	  sort -n $$tempfile$numcols -o $$tempfile$numcols
	  numcols=$(($numcols + 1))
	done
	numrows=$(($numrows + 1 ))
    done < $2

    med=$(($numrows / 2 + 1))
    count=0
    while (($count < $numcols))
    do
	sum=0
	tmpcnt=0
	while read line
	do
	  sum=$(($sum + $line)) #sums all values from column
	  tmpcnt=$(($tmpcnt + 1))
	  if [[ $med == $tmpcnt ]]  #finds median value
	  then
		medArray[$count]=$line #makes array of medians
	  fi
	done < $$tempfile$count	
	avg=$(($sum / $numrows))
	rem=$(($sum % $numrows))
	while (($rem >= ($numrows / 2))) #checks if average needs rounded up
	do
	  avg=$(($avg + 1))
	  rem=0
	done
	avgArray[$count]=$avg  #makes array of averages
	count=$(($count + 1))
    done

	count=0
	echo "Averages:"
	while (($count < $numcols)) #prints averages
	do
	 echo -e -n "${avgArray[$count]} \t"
	 count=$(($count + 1))
	done
	echo -e "\n"

	count=0
	echo "Medians:"
	while (($count < $numcols)) #prints medians
	do
	 echo -e -n "${medArray[$count]} \t"
	 count=$(($count + 1))
	done
	echo -e "\n"

	count=0
	while (($count < $numcols)) #deletes temp files
	do
	   rm -f $$tempfile$count
	   count=$(($count + 1))
	done
	echoerr 0
fi
